
-- INSERINDO PERFIL
INSERT INTO PERFIL (ID, STATUS, VERSAO, DESCRICAO, NOME) VALUES (1, 'ATIVO', 0, 'ADMINISTRADOR', 'ADMINISTRADOR');

-- INSERINFO USUÁRIO
INSERT INTO USUARIO (ID, STATUS, VERSAO, SENHA, PERFIL_ID, NOME_COMPLETO, EMAIL) VALUES (1, 'ATIVO', 0, '202cb962ac59075b964b07152d234b70', 1, 'Usuário administrador', 'user@admin');

-- INSERINDO PÁGINAS
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (1, 'ATIVO', 0, 'Cadastrar Página', 'CADASTRAR_PAGINA', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (2, 'ATIVO', 0, 'Editar Página', 'EDITAR_PAGINA', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (3, 'ATIVO', 0, 'Listar Página', 'LISTAR_PAGINA', 'Descrição');

INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (4, 'ATIVO', 0, 'Cadastrar Perfil', 'CADASTRAR_PERFIL', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (5, 'ATIVO', 0, 'Editar Perfil', 'EDITAR_PERFIL', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (6, 'ATIVO', 0, 'Listar Perfil', 'LISTAR_PERFIL', 'Descrição');

INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (7, 'ATIVO', 0, 'Cadastrar Usuário', 'CADASTRAR_USUARIO', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (8, 'ATIVO', 0, 'Editar Usuário', 'EDITAR_USUARIO', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (9, 'ATIVO', 0, 'Listar Usuário', 'LISTAR_USUARIO', 'Descrição');

--

INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (10, 'ATIVO', 0, 'Cadastrar Alternativa', 'CADASTRAR_ALTERNATIVA', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (11, 'ATIVO', 0, 'Editar Alternativa', 'EDITAR_ALTERNATIVA', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (12, 'ATIVO', 0, 'Listar Alternativa', 'LISTAR_ALTERNATIVA', 'Descrição');

INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (13, 'ATIVO', 0, 'Cadastrar Categoria', 'CADASTRAR_CATEGORIA', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (14, 'ATIVO', 0, 'Editar Categoria', 'EDITAR_CATEGORIA', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (15, 'ATIVO', 0, 'Listar Categoria', 'LISTAR_CATEGORIA', 'Descrição');

INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (16, 'ATIVO', 0, 'Cadastrar Prova', 'CADASTRAR_PROVA', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (17, 'ATIVO', 0, 'Editar Prova', 'EDITAR_PROVA', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (18, 'ATIVO', 0, 'Listar Prova', 'LISTAR_PROVA', 'Descrição');

INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (19, 'ATIVO', 0, 'Cadastrar Questão', 'CADASTRAR_QUESTAO', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (20, 'ATIVO', 0, 'Editar Questão', 'EDITAR_QUESTAO', 'Descrição');
INSERT INTO PAGINA (ID, STATUS, VERSAO, NOME, NOME_IDENTIFICADOR, DESCRICAO) VALUES (21, 'ATIVO', 0, 'Listar Questão', 'LISTAR_QUESTAO', 'Descrição');

-- RELACIONANDO USUÁRIO E PÁGINAS
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	1	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	2	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	3	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	4	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	5	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	6	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	7	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	8	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	9	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	10	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	11	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	12	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	13	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	14	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	15	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	16	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	17	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	18	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	19	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	20	);
INSERT INTO USUARIO_PAGINA(USUARIO_ID, PAGINA_ID) VALUES (1,	21	);

INSERT INTO CATEGORIA (STATUS, VERSAO, DESCRICAO, NOME) VALUES ('T', 1, 'Categoria referente a provas de certificação', 'Certificação');